---
- name: Ping server
  hosts: all
  tasks:
    - name: Ping
      command: cat /etc/os-release
      register: ping_output
    - name: print output
      debug:
        msg: '{{ ping_output }}'
    - name: Run python file
      script: test.py
      register: test_result
    - name: print output
      debug:
        msg: '{{ test_result }}'
