- name: Windows Ping
  hosts: win
  gather_facts: yes
  ignore_errors: yes
  tasks:
    - name: Windows ping check
      win_ping:
      
    - name: print output
      debug:
        msg: '{{ ansible_hostname }} - {{ ansible_host }} | {{ ansible_connection }} | {{ ansible_os }} | {{ ansible_distribution }}'
